name: ai_campus_rise_example
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipython
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda
  - nb_conda_kernels
  - nbconvert=5
  - nbformat
  - numpy=1.19.0
  - pandas
  - pip
  - pytest
  - scikit-image
  - scikit-learn=0.20
  - scipy
  - seaborn
  - traits
  - plotly
  - pip:
    - duecredit
    - keras
    - joblib
    - nbval
    - nibabel
    - nilearn
    - nipy
    - nose
    - tensorflow==1.14.0
    - RISE
